spring:
  r2dbc:
    url: { url }
    host: { host }
    port: { port }
    username: { username }
    password: { password }
    database: { database }
  sql:
    init:
      mode: always
      platform: postgresql
  webflux:
   base-path: /access-hub
server:
  port: 8080

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG


jwt:
  secret: { key }
  expiration: 120000
  refreshTokenExpiration: 86400000