spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    host: ${SPRING_R2DBC_HOST}
    port: ${SPRING_R2DBC_PORT}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    database: ${SPRING_R2DBC_DATABASE}
  sql:
    init:
      mode: always
      platform: postgresql
  webflux:
    base-path: /access-hub

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:120000}
  refreshTokenExpiration: ${JWT_REFRESH_EXPIRATION:86400000}
